### PR TITLE
PIRATE ENGLISH 🏴‍☠️🏴‍☠️🏴‍☠️

### PR DESCRIPTION
**Pull request by realeatham**

### CODE REVIEW

**Comment by TheEntropyShard** [comment]
Arr! It is unfinished!

**Comment by realeatham** [comment]
Oh I see the problem

**Comment by realeatham** [comment]
I was editing off an outdated fork

**Comment by TheEntropyShard** [comment]
image
This is where you missed a line

**Comment by realeatham** [comment]
I'm done now finally

**Comment by TheEntropyShard** [comment]
Thank you!

**Pull request merged**
