### PR TITLE
Disable `modal` On `JDialog`ues

### PR DESCRIPTION
**Pull request by coolGi69**
Currently, when another window (dialogue) is open, the parent window is no longer able to be interacted with.\
This could cause slight annoyances to the user, for example they could be editing the mods on an instance, then trying to run the game while doing so.\
So this is a small QOL pr to fix that.

This also adds the Unix executable flag to the `gradlew` file, as it was missing. I didn't think it was a big enough change to deserve its own PR, so it's bundled in here.

### CODE REVIEW

**Comment by TheEntropyShard** [comment]
I dont think that disabling modality for all dialogs is a good decision. Some dialogs were made modal on purpose, such as ProgressDialog or UpdateDialog or SelectIconDialog.
<br>
> This could cause slight annoyances to the user, for example they could be editing the mods on an instance, then trying to run the game while doing so.

Dont you edit mods, then close settings and then run the game? My intention was that user modifies something and everything is saved **before** running the game.

**Comment by coolGi69** [comment]
> I dont think that disabling modality for all dialogs is a good decision. Some dialogs were made modal on purpose, such as ProgressDialog or UpdateDialog or SelectIconDialog.

Alright, maybe adding a boolean in the constructor (with its default value being disabling touching the parent window) so it could be enabled/disabled per window.

<br/>

> > This could cause slight annoyances to the user, for example they could be editing the mods on an instance, then trying to run the game while doing so.
>
> Dont you edit mods, then close settings and then run the game? My intention was that user modifies something and everything is saved before running the game.

It may just be me, but I usually have the mods panel open to enable & disable mods and quickly launch the game.\
I know that certain stuff saves when menus close rather than when they are toggled (such as the mod loader version), but those stuff could be changed to save when modified.

<br/>

The only real thing that I want to be used is the instance config with the main page to launch it.

**Comment by TheEntropyShard** [comment]
Ok, I will look into it later.
<br>

Could you elaborate on this?
> The only real thing that I want to be used is the instance config with the main page to launch it.

**Comment by TheEntropyShard** [comment]
Also, even if you make settings dialog not modal, the main window will still be behind the settings dialog. Settings dialog either needs to be made a separate JFrame or not have parent.

**Comment by coolGi69** [comment]
Here is my use case of it.

Let's say I'm trying to figure out what mod is causing the very fast speed, but I didn't know this name.\
When I'm trying to do a [binary search](https://tenor.com/ja/view/binary-search-sequence-search-gif-20595028) to attempt to find it, currently I have to keep on closing and opening the menu.\
If the main window (which is where the launch button is) was still intractable while toggling mods, the process would be a lot quicker.

Here is a video containing how much faster it is without having to close and reopen the menu:
https://github.com/user-attachments/assets/d97ed1bb-656b-47df-9089-f3a24a74c4f2

Versus how fast it is with:
https://github.com/user-attachments/assets/209569a2-d432-4a6f-bc41-2013dc578e97

<br/>

It may be better to only have the settings menu for the instance accessible rather than everything, but it'd just make life easier if this were changed.

**Comment by coolGi69** [comment]
(I'll update this PR later today when I have more time to implement it so that it's only possible on the instance settings menu)

**Comment by coolGi69** [comment]
Fixed to only disable modal on the settings menu.

Also fixed the bug where if the mod version isn't set when initially setting which loader to use.

**Comment by TheEntropyShard** [comment]
LGTM, thank you!

**Pull request merged**
