### PR TITLE
Unmerge subprocess streams and use ERROR level for err stream

### PR DESCRIPTION
**Pull request by StartsMercury**
~~As of now, this is not needed.~~ or maybe not it seems

### CODE REVIEW

**Comment by TheEntropyShard** [comment]
This might be actually useful I want exception logs from the game display with error color in launcher console

**Comment by TheEntropyShard** [comment]
Could you please explain me the logic of the new implementation of `ProcessReader#read` method?

**Comment by StartsMercury** [comment]
In each iteration of the loop:
 * It checks if `in` is ready, if it is then it'll read the next line (if any)
 * It checks if `err` is ready, if it is then it'll read the next line (if any)
This is so either stream's output appear, mostly, in order.

If either `in` or `err` produced a `null` line (end of stream), it'll then read the other stream until it too ends.

The implementation can rewritten to be more readable:
```
// fair line retrieval for both streams
while (inNotDone || errNotDone) {
    if (in.isReady()) {
        if ((line = in.nextLine()) != null) {
            // use `line`
        } else {
            inNotDone = false;
        }
    }
    if (err.isReady()) {
        if ((line = err.nextLine()) != null) {
            // use `line`
        } else {
            errNotDone = false;
        }
    }
}

// handle remaining lines
if (inNotDone) {
    while ((line = in.nextLine()) != null) {
        // use `line`
    }
}
if (errNotDone) {
    while ((line = err.nextLine()) != null) {
        // use `line`
    }
}
```

**Comment by StartsMercury** [comment]
> Checked, this is kinda broken

Yeah, my assumptions must be wrong on exit condition. It reminds me, I was only testing if the application hangs and forgot to consider exiting. I'll look into a fix when I find the time.

**Comment by acodili-jg** [comment]
It seems the streams never return EOF indicators on exit. The fix is to check if the process is still alive; otherwise, stop. It also seems that no more data after the process is detected dead so there's no need to log at that point.

**Comment by acodili-jg** [comment]
It seems the streams never return EOF indicators on exit. The fix is to check if the process is still alive; otherwise, stop. It also seems that no more data after the process is detected dead so there's no need to log at that point.

**Comment by StartsMercury** [comment]
It seems the streams never return EOF indicators on exit. The fix is to check if the process is still alive; otherwise, stop. It also seems that no more data after the process is detected dead so there's no need to log at that point.

**Comment by TheEntropyShard** [comment]
This seems to be still broken :(

**Comment by StartsMercury** [comment]
:'), it could be a me problem or there is some os-specific behavior that I haven't accounted. This PR is not that high priority rn but hopefully, hopefully, I can figure out why this stuff still brokering ;-;

**Comment by TheEntropyShard** [comment]
Which OS are you using? Linux, I suppose. I am using Windows.

**Comment by StartsMercury** [comment]
> Which OS are you using? Linux, I suppose. I am using Windows.

Wait- huh. I am on Windows, but it was working for me...or have I hallucinated it working. I'll test again later. Just checking, is your copy have javadoc?

**Comment by TheEntropyShard** [comment]
It does

**Comment by StartsMercury** [comment]
> Checked, this is kinda broken to be honest. I used a manual crash button in game to test, with the old implementation when I press "OK" in game error dialog, the game process stops and I get all output from it and exit code message is also there. But with the new implementation, when I press "OK", the process does not end and I have to manually stop it from my OS task manager and the error output is not full and there is no messages when process ends as well. 

Is this the same broken stuff?
* not all the outputs are showing when closing
* the process did not stop
* the process exit code did not print (caused by above)

**Comment by TheEntropyShard** [comment]
Yes

**Comment by StartsMercury** [comment]
I've done some searching and it appears there's a different implementation (without using new threads)
<https://codereview.stackexchange.com/q/7631>

Though for it to apply here, the log consumers accepts one line at a time, either the log consumers should accept incomplete lines or we have to manually buffer the line. Some lines can be way to long, filling up the native stream buffers (process out and err) and causing it to freeze. This is likely what's happening in your test. (Why is this not mentioned in the documentation ;-;)

**Comment by TheEntropyShard** [comment]
What's up with using two threads for reading output?

**Comment by StartsMercury** [comment]
> What's up with using two threads for reading output?

Well if you don't mind, we could go with the 1-2 threads implementation (we can use an extra one instead of two). But I doubt we can use `readLine` from buffered reader. The underlying implementation of the logger might be able to handle the asynchronous logging (race-condition; todo link relevant crlauncher code)

A line could still probably be too long (until the next newline), filling up the native stream buffer and causing problems. A separate problem that affects `readLine` implementations, I think.

**Comment by TheEntropyShard** [comment]
I guess this is not needed anymore, because I looked how other launchers handle errors and exceptions from the game, and it seems that they all use only stdin and just look for patterns in log lines. For example, MultiMC: [MinecraftInstance.cpp#L773](https://github.com/MultiMC/Launcher/blob/bb04cb09a37e4396ba09068e7d8691ceb6e3cfdc/launcher/minecraft/MinecraftInstance.cpp#L773)

image

**Pull request closed without merging**
